name: Pull request
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  pull_request:
    branches:
      - 'main' 

jobs:
  Push-Action:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls -la ${{ github.workspace }}  
      - run: python3 .buildscripts/pr.py
      - run: echo "🍏 This job's status is ${{ job.status }}."